name: actionlint

on:
  push:
    branches: [master]
    paths: ['.github/workflows/**']
  pull_request:
    paths: ['.github/workflows/**']

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        run: docker run --rm -v "$PWD":/repo -w /repo rhysd/actionlint:1.7.7 -color
